### ISSUE TITLE
can't resolve vue2-highcharts

### ISSUE THREAD

**Issue by willrpike** [superman66/vue-highcharts#1]
After installation with npm I'm not seeing a dist folder being generated. 

This is making it so that I can't resolve vue2-highcharts

**Comment by superman66** [comment]
@willrpike thank you to oepn this issue. 
This is my mistake, I forgot upload the dist dir.
I had already fixed this. 
Please `npm install vue2-highcharts` again.

**Comment by Rogant** [comment]
i have the issue with the 1.0.4

**Comment by superman66** [comment]
@Rogant It's fixed
