### ISSUE TITLE
setCategories for xAxis...

### ISSUE THREAD

**Issue by Truman55** [superman66/vue-highcharts#14]
How I can use native Highchart method for xAxis - setCategories?
I've tried using delegateMethod, but it is not work. 
Thanks.

**Comment by superman66** [comment]
according to highcharts [setCategories Demo](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/axis-setcategories/), you can find out use `chart.xAxis[0].setCategories();` to update categories.
so in the component, you can do that:
```
lineCharts.getChart().xAxis[0].setCategories(['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D']);
```
I alos update the demo. you can check it out.

**Comment by Truman55** [comment]
Thanks for your reply. I also was able to make it using delegateMethod.
`chartName.delegateMethod('update', ({
    xAxis: {
        categories: []
    }
}));`

But maybe your method is more correct

**Comment by superman66** [comment]
anyway, it works
