### ISSUE TITLE
Change data

### ISSUE THREAD

**Issue by joshharington** [superman66/vue-highcharts#16]
How do I change the data of a series? I am able to remove series using the removeSeries() function but am unable to add series with data back.

**Comment by superman66** [comment]
you can use `addSeries()`

**Comment by joshharington** [comment]
@superman66 I am using addSeries() and it adds to the legend but no data shows.

**Comment by superman66** [comment]
I update demo. Added `removeSeries()` and `addSeries()`, you can see [demo](https://chenhuichao.com/vue-highcharts/)

**Comment by bmarkovic** [comment]
Your demo link doesn't work. Please consider using JSFiddle, Codepen or CodeSandbox where demos won't just mysteriously disappear after a couple of months, code will be instantly visible along with the results and people can continue experimenting in the browser with your demo to tune it to their needs before they can get back to work.

This is doubly so for fickly, capricious, DOM-bound software from a different era like Highcharts.

**Comment by superman66** [comment]
@bmarkovic Thank you for your suggestion!
I have create a demo in CodeSanbox: [Vue-Highcharts Demo](https://codesandbox.io/s/jjyqvv0k13)
