### ISSUE TITLE
Global Highcharts methods, e.g. setOptions

### ISSUE THREAD

**Issue by dpgalloway** [superman66/vue-highcharts#26]
How can I apply global highcharts methods? For example, I'd like to set the thousands separator to comma, which in the Highcharts documentation is done by doing this (http://jsfiddle.net/highcharts/eeDnv/): 

```
Highcharts.setOptions({
    lang: {
        decimalPoint: '.',
        thousandsSep: ','
    },
});
```

I've tried this.$refs.highchart.delegateMethod('setOptions')... but that gives an error (can't apply undefined). I've also tried this.$refs.highchart.chart.setOptions()... but that also gives an error that setOptions is not a function.

**Comment by superman66** [comment]
`this.$refs.highchart` this Highchart Instance is correct?

**Comment by superman66** [comment]
hey @dpgalloway, I found it works below:
in Javascript, you can use like normal Highcharts usage,
```js
Highcharts.setOptions({
  lang: {
    drillUpText: 'back',
  },
})
```
in HTML:  you should add `Highcharts` as props
```html
<vue-highcharts :Highcharts="Highcharts" :options="options" ></vue-highcharts>
```

**Comment by dpgalloway** [comment]
@superman66 Thank you for the answer, but I couldn't get that to work (error that Highcharts is undefined). I ended up just using vanilla Highcharts since my needs are fairly simple and don't need to rely on Vue. However, if you have a snippet of working code using the method you described above, others may find it useful (could also add to documentation).

**Comment by superman66** [comment]
you can see this demo [LoadModuleChart.vue](https://github.com/superman66/vue-highcharts/blob/master/demo/LoadModuleChart.vue#L14)

**Comment by superman66** [comment]
@dpgalloway hi, has your problem been solved?
