### ISSUE TITLE
Unable to use Vue2-highcharts with nuxt.js

### ISSUE THREAD

**Issue by creativenoobie** [superman66/vue-highcharts#28]
Hey,

I was trying to use this plugin with Nuxt.js and had no luck so far even with `<no-ssr>` option.

![capture](https://user-images.githubusercontent.com/23532769/37290831-4dc39322-2633-11e8-9052-dab01d21786f.PNG)

Can you please check the issue?

Thanks in advance

**Comment by superman66** [comment]
@creativenoobie sorry, I have been busy those days.
I will check this issue in this weekend.

**Comment by a1265137718** [comment]
hi, have this problem resolved?

**Comment by Geminii** [comment]
@superman66 Same problem here, can you fix it faster ? :)
Even if vue2-highcharts loaded with `ssr: false`, it not working :(

`function addStyle (obj /* StyleObjectPart */) {
  var update, remove
  var styleElement = document.querySelector('style[data-vue-ssr-id~="' + obj.id + '"]') // document is not defined at line 1127`

**Comment by superman66** [comment]
@Geminii @a1265137718 @creativenoobie 
I have add a repo for using vue2-highcharts in nuxt.js. [vue-nuxt-demo](https://github.com/superman66/vue-nuxt-demo)
or you can see README.md [using-with-nuxt.js](https://github.com/superman66/vue-highcharts#using-with-nuxtjs)

About how to define a globle component in nuxt.js, you can see https://github.com/nuxt/nuxt.js/issues/421.

**Comment by Geminii** [comment]
@superman66 Hi again, 
Works perfectly, thanks a lot for your work :) 

Thanks to add precision about documentation for nuxt and requirements.
