### ISSUE TITLE
尺寸如何处理

### ISSUE THREAD

**Issue by xdwxls** [superman66/vue-highcharts#29]
假设我有个饼图，外围宽高都是150px，应该如何修改呢？目前class 为vue-highcharts 生成的宽高好大

**Comment by superman66** [comment]
https://github.com/superman66/vue-highcharts/blob/master/README.md#props 你可以自定义class 和 style 控制宽高

**Comment by superman66** [comment]
@xdwxls 不知道问题解决了吗？如果解决了，可以 issue 关闭。
