### ISSUE TITLE
Change default border style

### ISSUE THREAD

**Issue by lopezchr** [superman66/vue-highcharts#30]
When the chart is rendered, it use a default border style that is not compatible with a lot of style guide lines. I had to use this to override the default styles:
`
.vue-highcharts {
    border: 0px;
    border-radius: 0px;
    box-shadow: 0 0 0;
    margin: 0px;
  }
`

**Comment by superman66** [comment]
https://github.com/superman66/vue-highcharts#props
you can use custom classname

**Comment by superman66** [comment]
@lopezchr can it works? if works, please close this issue. thank you.
