### ISSUE TITLE
Setting drill down in option and do mergeOption not working

### ISSUE THREAD

**Issue by HarisHashim** [superman66/vue-highcharts#36]
I know that drill down is working because it works if I set directly in myOptions inside template

```
<template>
      <vue-highcharts :highcharts="Highcharts" :options="myOptions" ref="vueHighcharts"/>
</template>```
```

```
// in script
data() {
    return {
      // ...
      myOptions: {
          // ...
      }
   }
}
```

However, I want to set drill down dynamically by setting myOptions and mergeOption. And this does not work!

```
this.myOptions.drilldown.series = this.chartData.drilldown.series;
this.hichart.mergeOption(this.options);
```

Any guide how to do this?

Thanks in advance
Haris

**Comment by superman66** [comment]
Can you provide any online code? Or you can fork [Vue-highcharts Demo](https://codesandbox.io/s/jjyqvv0k13)

**Comment by HarisHashim** [comment]
Sorry, was sidetracked by other stuff. Will get back once I got something working with the demo fork!

**Comment by HarisHashim** [comment]
Hi again @superman66 , took me so long to get back to you.

It turns out mergeOption function is working when I modify the vue-highcharts-demo code given by you. 

Since I have problem with sandbox link that you share with me. I put my testing code in [Github](https://github.com/HarisHashim/vue-highcharts-demo). My test code is in [LoadModuleChart](https://github.com/HarisHashim/vue-highcharts-demo/blob/master/src/components/LoadModuleChart.vue).

I add 2 button to change the series and drilldown serries. The functions to change is in methods

Thanks and I am going to close this issue. Must be something wrong with my code since it works in the demo.
