### ISSUE TITLE
class="vue-highcharts" remove rounded corners works in dev, but not in build.

### ISSUE THREAD

**Issue by Davidriquelme** [superman66/vue-highcharts#39]
In an attempt to eliminate the round corners, shadows, margins, paddings, etc.  I did this that worked in development mode:

file: custom.css:

 .vue-highcharts {
    width: 100%;
    display: inline-block;
    margin: 0;
    border: 0px solid rgba(0, 0, 0, 0);
    border-radius: 0px;
    box-shadow: 0 0 0px rgba(0, 0, 0, 0);
    padding: 0px;
    background: #fff;
}
result:
![image](https://user-images.githubusercontent.com/12628676/39382959-cf2874f4-4a3d-11e8-9e8f-c83b55f17439.png)

but build mode still resulting in this:
![image](https://user-images.githubusercontent.com/12628676/39383450-a6e8de32-4a3f-11e8-850e-87d3c2b1211d.png)

which are best practices to style the highcharts-class ?

**Comment by superman66** [comment]
It seems to custom css does't  work in build mode. Have you check custom css import in build mode?

**Comment by superman66** [comment]
@Davidriquelme in the last version, I have removed the default styles.
