### ISSUE TITLE
I'm getting a bunch of errors. Is it normal?

### ISSUE THREAD

**Issue by cosbgn** [superman66/vue-highcharts#4]
Hi. 

I've installed `vue-highcharts` just adding `<script src="/static/js/vue-highcharts/dist/vue-highcharts.js"></script>` to my html file, however I get many errors like `webpack_require`.

Check here: https://snag.gy/s9Xw4A.jpg 

Is it normal? Why does it happen?

Also is there a documentation/guide on how to use this package with axios to plot some data I have in my database?

Thanks

**Comment by willrpike** [comment]
Hi

Based on your screenshot you are only getting one error, that's just a stack trace along with it. 

The error you are getting is a highcharts specific error, it looks like you might be defining it twice on your page https://www.highcharts.com/errors/16

Hope this helps

**Comment by cosbgn** [comment]
Hi! I double checked and I have the script only once (i.e. once the vue-highcharts and once the highcharts). When I remove the highcharts the error goes away. Does the vue-highcharts includes the highchart library directly?

**Comment by superman66** [comment]
@Cosbgn the vue-highcharts has included the highcharts library.
