### ISSUE TITLE
Creating new project and adding dependency  "vue2-highcharts": "^1.2.0" give error

### ISSUE THREAD

**Issue by HarisHashim** [superman66/vue-highcharts#41]
The error is:
```
This dependency was not found:

* vue2-highcharts in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/ChartWidget.vue

To install it, you can run: npm install --save vue2-highcharts
```

I have old project that works. So thinking that this is version problem, I tried "vue2-highcharts": "1.1.19" in package.json and that works! 

Must be latest version problem.

**Comment by superman66** [comment]
@HarisHashim My mistakes. the latest version vue2-highcharts@1.2.3 works.

**Comment by HarisHashim** [comment]
It is working now with the latest. Thanks for the quick resolution.
