### ISSUE TITLE
Missing(?) Highcharts methods

### ISSUE THREAD

**Issue by realcheese** [superman66/vue-highcharts#5]
Please correct me if I am wrong but I am trying to use some of Highcharts methods such as `update()` but I receive an error message that it is undefined. I'm also unable to access the `series` property (I want to use `setData()`). 

I've tried `addSeries()` and it works. It seems like VueHighcharts.vue contains a small # of the methods listed in Highcharts API. If I need to use these methods, what is the best way for me to do so? Should I update my VueHighcharts.vue file?

Thank you.

**Comment by superman66** [comment]
if you want to use some of Highcharts methods, you can try `delegateMethod()`.
such as `update()`, you can use `delegateMethod('update')`.

**Comment by realcheese** [comment]
Thanks I'll give it a shot!

________________________________
